# --- Academic Pages minimal config ---

# IMPORTANT: use remote_theme, not theme
remote_theme: academicpages/academicpages.github.io

title: Chenhao Chiu

# Site settings
locale: en-US
markdown: kramdown
permalink: /:categories/:title/

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache


# Navigation (Academic Pages uses this via Minimal Mistakes)
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /pub/

# Author (shows in sidebar)
avatar: "/assets/images/Profile_CHIU2.png"
author:
  name: 邱振豪
  bio: "Speech Behavior and Science Lab, NTU"
  email: "chenhaochiu@ntu.edu.tw"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:chenhaochiu@ntu.edu.tw"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chenhaochiu"




fontawesome: true

minimal_mistakes_skin: default
include:
  - _pages
  - assets

