theme: jekyll-theme-dinky
title: Chenhao Chiu
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Publications"
    url: "/pub/"

header_pages:
  - index.md
  - about.md
  - portfolio.md
